FROM node:16-alpine as build-stage
WORKDIR /app
COPY package*.json ./
COPY tsconfig.json ./
RUN NODE_ENV=development npm i
COPY . .
RUN npm run build

FROM nginx:1.22.1-alpine as prod-stage
COPY --from=build-stage /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]